<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NPBENJ3" failures="2" tests="2" name="Assertions Test" time="0.038" errors="0" timestamp="2021-09-01T17:38:12 EDT">
  <testcase classname="testcases.SoftAssertTest" name="validate" time="0.009">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [xyz] but found [abc],
	Not Mathematically possible expected [true] but found [false],
	404-Error">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [xyz] but found [abc],
Not Mathematically possible expected [true] but found [false],
404-Error
at testcases.SoftAssertTest.validate(SoftAssertTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate -->
  <testcase classname="testcases.HardAssertTest" name="doLogin" time="0.001">
    <failure type="java.lang.AssertionError" message="Custom Err Message - 404 error">
      <![CDATA[java.lang.AssertionError: Custom Err Message - 404 error
at testcases.HardAssertTest.doLogin(HardAssertTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Assertions Test -->
